# **Scalar Value**

In [3]:
import numpy as np;

num : np.ndarray = np.array(1000); # N-Dimensional Array

print(f"Object: {num}");

print(f"Object Shape: {num.shape}");

print(f"Object Type: {num.dtype}");

print(f"Object Type With Global Function: {type(num)}");

print(f"Number Of Dimension: {num.ndim}");

print(f"Total Items In Array: {num.size}");

print(f"Object Item Size: {num.itemsize}");

Object: 1000
Object Shape: ()
Object Type: int64
Object Type With Global Function: <class 'numpy.ndarray'>
Number Of Dimension: 0
Total Items In Array: 1
Object Item Size: 8


# **Vector Type**

In [4]:
num2 : np.ndarray = np.array([1,2,3,4]);

print(f"Object: {num2}");

print(f"Object Shape: {num2.shape}");

print(f"Object Type: {num2.dtype}");

print(f"Object Type With Global Function: {type(num2)}");

print(f"Number Of Dimension: {num2.ndim}");

print(f"Total Items In Array: {num2.size}");

print(f"Object Item Size: {num2.itemsize}");

Object: [1 2 3 4]
Object Shape: (4,)
Object Type: int64
Object Type With Global Function: <class 'numpy.ndarray'>
Number Of Dimension: 1
Total Items In Array: 4
Object Item Size: 8


# **Matrix**

In [5]:
data = [[0, 1, 2, 3],
        [4, 5, 6, 7],
        [8, 9, 10, 11]];

num3 : np.ndarray = np.array(data);

print(f"Object: {num3}");

print(f"Object Shape: {num3.shape}");

print(f"Object Type: {num3.dtype}");

print(f"Object Type With Global Function: {type(num3)}");

print(f"Number Of Dimension: {num3.ndim}");

print(f"Total Items In Array: {num3.size}");

print(f"Object Item Size: {num3.itemsize}");

Object: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Object Shape: (3, 4)
Object Type: int64
Object Type With Global Function: <class 'numpy.ndarray'>
Number Of Dimension: 2
Total Items In Array: 12
Object Item Size: 8


# **Numpy Arange With NDArray Types**

In [14]:
from nptyping import NDArray, Shape, UInt64;

data : NDArray[Shape["10"], UInt64] = np.arange(10);

print(data);

[0 1 2 3 4 5 6 7 8 9]


In [15]:
from nptyping import NDArray, Shape, UInt64;

data : NDArray[Shape["10"], UInt64] = np.arange(1, 11);

print(data);

print(data + 5);

[ 1  2  3  4  5  6  7  8  9 10]
[ 6  7  8  9 10 11 12 13 14 15]


In [16]:
newData : list[int] = list(range(1, 11));

print([ i + 5 for i in newData ]); # List Comprehensive

[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


In [17]:
%%time

data : NDArray[Shape["10000000"], UInt64] = np.arange(1, 10000000);

data + 5

CPU times: user 13.2 ms, sys: 16.4 ms, total: 29.7 ms
Wall time: 31.4 ms


array([       6,        7,        8, ..., 10000002, 10000003, 10000004])

In [18]:
%%time

data : list[int] = list(range(1, 10000000));

[ i + 5 for i in data ] # Time Taken

CPU times: user 430 ms, sys: 446 ms, total: 876 ms
Wall time: 880 ms


[6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,


# **Numpy Advanced Operations Vs List Operations**

In [19]:
data : list[int] = list(range(1,21));

print(data);

print(data[5:11]);

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[6, 7, 8, 9, 10, 11]


In [20]:
nData : NDArray[Shape["20"], UInt64] = np.arange(1,21);

print(nData);

print(nData[5:11]);

nData[5:11] = 1000;

print(nData);

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 6  7  8  9 10 11]
[   1    2    3    4    5 1000 1000 1000 1000 1000 1000   12   13   14
   15   16   17   18   19   20]


# **Boolean Slicing**

In [21]:
from nptyping import Bool, UInt64;

stateBank : NDArray[Shape["4"], UInt64] = np.array([1,7,8,10]);

select : NDArray[Shape["4"], Bool]= np.array([True, False, False, True]);

print(stateBank[select]); # Boolean Slicing

[ 1 10]


In [22]:
stateBank : NDArray[Shape["10"], UInt64] = np.array([1,2,3,4,5,6,7,8,9,10]);

print(stateBank % 2 == 0);

[False  True False  True False  True False  True False  True]


In [23]:
stateBank : NDArray[Shape["10"], UInt64] = np.array([1,2,3,4,5,6,7,8,9,10]);

print(stateBank[stateBank % 2 == 0]);

[ 2  4  6  8 10]


# **Numpy 1D Function**

In [24]:
stateBank : NDArray[Shape["4"], UInt64] = np.array([1,7,8,10]);

bank : NDArray[Shape["100"], UInt64] = np.random.randint(1, 100, 20); # Start , End & Quantity

print(stateBank);

print(bank);

[ 1  7  8 10]
[ 8 73  2 61 37  1 35 19 59 57 73 27 39  7 12 38 80 37 39  8]


In [26]:
print(np.in1d(stateBank, bank));

print(stateBank[np.in1d(stateBank, bank)]);

[ True  True  True False]
[1 7 8]


In [27]:
print(np.intersect1d(stateBank, bank));

[1 7 8]


In [31]:
x : NDArray[Shape["5"], UInt64] = np.array([1,3,4,9,7]);

y : NDArray[Shape["5"], UInt64] = np.array([6,3,2,5,100]);

print(x);

print(y);

print(np.where(x > y, x, y));

print(np.where(x < y, x, y));

[1 3 4 9 7]
[  6   3   2   5 100]
[  6   3   4   9 100]
[1 3 2 5 7]


# **Numpy Array Types**

In [32]:
from typing import Any;

a : NDArray[Shape["Size, Size"], Any] = np.array([[1, 2, 3],
                                                  [4, 5, 6]]);
print(a);

a : NDArray[Shape["Size, Size"], Any] = np.array([[1, 2],
                                                  [4, 5]]);
print(a);

a : NDArray[Shape["Size, Size"], Any] = np.array([["A"],
                                                  ["B"]]);
print(a);

[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]
[['A']
 ['B']]


In [33]:
a : NDArray[Shape["*, *"], UInt64] = np.array([[1, 2, 3],
                                               [4, 5, 6]]);
print(a);

a : NDArray[Shape["*, *"], UInt64] = np.array([[1, 2],
                                               [4, 5]]);
print(a);

a : NDArray[Shape["*, *"], UInt64] = np.array([["A"],
                                               ["B"]]);
print(a);

[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]
[['A']
 ['B']]


In [34]:
np.who() # It's Provide Every Present NumPy Array's Information

Name            Shape            Bytes            Type

__              9999999          79999992         int64
num                              8                int64
num2            4                32               int64
num3            3 x 4            96               int64
_9              9999999          79999992         int64
nData           20               160              int64
_17 (__)        9999999          79999992         int64
stateBank       4                32               int64
select          4                4                bool
bank            20               160              int64
x               5                40               int64
y               5                40               int64
a               2 x 1            8                str32

Upper bound on total bytes  =       160000564


In [35]:
np.info(stateBank) # It's Provide Specific NumPy Array Information

class:  ndarray
shape:  (4,)
strides:  (8,)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x5945ee72acf0
byteorder:  little
byteswap:  False
type: int64


# **NumPy Any Dimension Array**

In [36]:
a : NDArray[Shape["Size"], UInt64] = np.arange(1, 5); # 1 Dimension Array

print(a);

b : NDArray[Shape["Size"], UInt64] = np.arange(1, 10);

print(b);

[1 2 3 4]
[1 2 3 4 5 6 7 8 9]


In [37]:
a : NDArray[Shape["Size , Size"], UInt64] = np.arange(3 * 3).reshape(3, 3); # 2 Dimensions Array

print(a);

b : NDArray[Shape["Size , Size"], UInt64] = np.arange(5 * 3).reshape(5, 3);

print(b);

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [38]:
a : NDArray[Shape["Size , Size , Size"], UInt64] = np.arange(2 * 3 * 3).reshape(2, 3, 3); # 3 Dimensions Array

print(f"{a}\n");

b : NDArray[Shape["Size , Size , Size"], UInt64] = np.arange(5 * 2 * 2).reshape(5, 2, 2);

print(b);

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]


In [39]:
b : NDArray[Shape["Size , Size , Size"], UInt64] = np.arange(5 * 2 * 2).reshape(5, 2, 2);

print(b[::2, ::, ::]); # 2D Array , Rows & Items In Row

[[[ 0  1]
  [ 2  3]]

 [[ 8  9]
  [10 11]]

 [[16 17]
  [18 19]]]


In [40]:
print(b[::3, ::, ::]);

[[[ 0  1]
  [ 2  3]]

 [[12 13]
  [14 15]]]


In [41]:
b : NDArray[Shape["Size , Size , Size"], Bool] = np.arange(5 * 2 * 2).reshape(5, 2, 2);

[b % 2 == 0]

[array([[[ True, False],
         [ True, False]],
 
        [[ True, False],
         [ True, False]],
 
        [[ True, False],
         [ True, False]],
 
        [[ True, False],
         [ True, False]],
 
        [[ True, False],
         [ True, False]]])]

In [42]:
print(b[b % 2 == 0]);

[ 0  2  4  6  8 10 12 14 16 18]


In [44]:
print(np.asarray((1,2,3))); # Convert In Array

np.asarray((1))

[1 2 3]


array(1)

In [45]:
print(np.zeros(10));

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [46]:
print(np.zeros((2, 2)));

[[0. 0.]
 [0. 0.]]


In [47]:
print(np.ones((2, 2)));

[[1. 1.]
 [1. 1.]]


In [48]:
x : NDArray[Shape["Size , Size , Size"], UInt64] = np.arange(5 * 2 * 2).reshape(5, 2, 2);

print(x);

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]


In [49]:
print(np.ones_like(x));

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


In [50]:
print(np.zeros_like(x));

[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]

 [[0 0]
  [0 0]]

 [[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]


In [51]:
print(np.full_like(x, 4)); # Array Convert Custom Number

[[[4 4]
  [4 4]]

 [[4 4]
  [4 4]]

 [[4 4]
  [4 4]]

 [[4 4]
  [4 4]]

 [[4 4]
  [4 4]]]


In [52]:
x : NDArray[Shape["Size , Size , Size"], UInt64] = np.arange(5 * 2 * 2).reshape(5, 2, 2);

print(x[[0, -1], ::, ::]); # Custom Indexing

[[[ 0  1]
  [ 2  3]]

 [[16 17]
  [18 19]]]


In [53]:
ndata : NDArray[Shape["20"], UInt64] = np.arange(1, 21);

print(ndata);

print(ndata.min());

print(ndata.max());

print(ndata.argmin()); # Return Index Of Min Value

print(ndata.argmax()); # Return Index Of Max Value

print(ndata.mean()); # Average Calculate Of All Elements

print(ndata.sum()); # Return Sum Of All Elements

print(ndata.cumsum()); # Return Cumulative Sum Calculate

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
1
20
0
19
10.5
210
[  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153 171
 190 210]
