In [3]:
import numpy as np;

# **Numpy Basic Array**

In [4]:
arr = np.array([1, 2, 3, 4]);

arr

array([1, 2, 3, 4])

In [5]:
myList = [1, 2, 3, 4]; # List

myList

[1, 2, 3, 4]

In [6]:
myList = [1, 2.5, "Hello", 4]; # In List Can Create Multi Data Types

myList

[1, 2.5, 'Hello', 4]

In [8]:
np.array(myList) # All The Data Types Have Been Changed In String Types In Array

array(['1', '2.5', 'Hello', '4'], dtype='<U32')

In [9]:
print(np.array([1,2.5,4])); # Bcz In Array Run Only Same Data Types (Float)

[1.  2.5 4. ]


In [10]:
l = [[1, 2, 3] , [4, 5, 6] , [7, 8, 9]];

l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
num = np.array(1000); # N-Dimensional Array

print(f"Object: {num}");

print(f"Object Shape: {num.shape}");

print(f"Object Type: {num.dtype}");

print(f"Object Type With Global Function: {type(num)}");

print(f"Number Of Dimension: {num.ndim}");

print(f"Total Items In Array: {num.size}");

print(f"Object Item Size: {num.itemsize}");

Object: 1000
Object Shape: ()
Object Type: int64
Object Type With Global Function: <class 'numpy.ndarray'>
Number Of Dimension: 0
Total Items In Array: 1
Object Item Size: 8


# **Vector Type**

In [13]:
num2 = np.array([1,2,3,4]); # 1 Dimensional Array

print(f"Object: {num2}");

print(f"Object Shape: {num2.shape}");

print(f"Object Type: {num2.dtype}");

print(f"Object Type With Global Function: {type(num2)}");

print(f"Number Of Dimension: {num2.ndim}");

print(f"Total Items In Array: {num2.size}");

print(f"Object Item Size: {num2.itemsize}");

Object: [1 2 3 4]
Object Shape: (4,)
Object Type: int64
Object Type With Global Function: <class 'numpy.ndarray'>
Number Of Dimension: 1
Total Items In Array: 4
Object Item Size: 8


# **Matrix Type**

In [14]:
l = [[1,2,3] , [4,5,6] , [7,8,9]] # Multi Dimensional List

l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [15]:
np.array(l) # 2 Dimensional Array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
data = [[0, 1, 2, 3],
        [4, 5, 6, 7],
        [8, 9, 10, 11]];

num3 = np.array(data);

print(f"Object: {num3}");

print(f"Object Shape: {num3.shape}");

print(f"Object Type: {num3.dtype}");

print(f"Object Type With Global Function: {type(num3)}");

print(f"Number Of Dimension: {num3.ndim}");

print(f"Total Items In Array: {num3.size}");

print(f"Object Item Size: {num3.itemsize}");

Object: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Object Shape: (3, 4)
Object Type: int64
Object Type With Global Function: <class 'numpy.ndarray'>
Number Of Dimension: 2
Total Items In Array: 12
Object Item Size: 8


# **Array Generation Function**

In [17]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
arr = np.arange(1, 11, 2);

arr

array([1, 3, 5, 7, 9])

In [19]:
np.zeros(6) # 1D Array Also Known as Vector

array([0., 0., 0., 0., 0., 0.])

In [23]:
arr = np.zeros((4, 8)); # 2D Array Also Known as Matrix (Rows & Columns)

arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [24]:
arr = np.ones((6, 6));

arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [25]:
np.linspace(1, 5, 2) # Linear Space

array([1., 5.])

In [26]:
np.linspace(1, 5, 3)

array([1., 3., 5.])

In [27]:
np.linspace(1, 5, 5)

array([1., 2., 3., 4., 5.])

In [28]:
arr = np.linspace(0, 1, 100);

arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

# **Random Generation Function**

In [33]:
np.random.rand(10) # Rand Returns Random Numbers (0 To 1)

array([0.92472402, 0.13684687, 0.07191074, 0.19280296, 0.97680244,
       0.29595352, 0.11722315, 0.77271279, 0.35843541, 0.29470879])

In [34]:
np.random.randn(10) # RandN Returns Standard Normal Random Numbers (Mostly -3 To 3)

array([ 0.03614049,  0.17004332,  0.65319714,  0.87244872, -0.1244087 ,
       -2.35914861,  0.85187873,  0.56727371, -1.12760971,  1.43673395])

In [31]:
np.random.randint(6)

5

In [36]:
np.random.randint(10, 20, 10) # Low Between High Numbers & Total Numbers

array([18, 15, 18, 19, 16, 16, 13, 11, 18, 14], dtype=int32)

# **Array Attributes**

In [37]:
arr = np.array([[1, 2, 3] , [4, 5, 6] , [7, 8, 9]]);

arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
arr.shape # Not Need To Add Brackets Bcz Its Attributes

(3, 3)

In [39]:
arr.size

9

In [40]:
arr.dtype

dtype('int64')

# **Array Methods**

In [41]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
arr.min()

np.int64(1)

In [43]:
int(arr.min())

1

In [44]:
int(arr.max())

9

In [45]:
arr.sum();

print(int(arr.sum()));

45


In [46]:
np.sum(arr, axis = 0)  # Horizontal (Column Wise) Sum

array([12, 15, 18])

In [47]:
np.sum(arr, axis = 1) # Vertical (Row Wise) Sum

array([ 6, 15, 24])

In [48]:
arr.mean()

np.float64(5.0)

In [49]:
float(arr.mean())

5.0

In [50]:
arr.std() # Standard Deviation

np.float64(2.581988897471611)

In [51]:
arr.argmax() # Returns Index Of The Largest Value In The Array

np.int64(8)

In [52]:
arr.argmin() # Returns Index Of The Smallest Value In The Array

np.int64(0)

# **Reshaping & Resizing**

In [53]:
arr = np.arange(1, 31);

arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [55]:
arr = arr.reshape(6, 5); # Rows & Columns (Remember: All Values Must Fit Exactly! No Extra Or Missing)

print(arr);

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
