In [1]:
import numpy as np;

In [2]:
sudo = np.array([ # Valid Sudoku
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
]);

sudo

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [3]:
int(sudo.sum()) # All Elements Sum

405

In [4]:
np.sum(sudo, axis = 1) # 1 Axis Present Rows

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [5]:
np.sum(sudo, axis = 0) # 0 Axis Present Columns

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [6]:
checkRow = np.sum(sudo, axis = 1);

checkRow == 45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [7]:
checkCol = np.sum(sudo, axis = 0);

for i in checkCol:
    if i != 45:
        print("Sudoku Is Not Valid For Columns");
        break
else:
    print("Sudoku Is Valid For Columns");

Sudoku Is Valid For Columns


In [8]:
for i in checkRow:
    if i != 45:
        print("Sudoku Is Not Valid For Rows");
        break
else:
    print("Sudoku Is Valid For Rows");

Sudoku Is Valid For Rows


In [9]:
sudoNew = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 3],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
]);

sudoNew

array([[5, 3, 4, 6, 7, 8, 9, 1, 3],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [10]:
checkRow = np.sum(sudoNew, axis = 1);

for i in checkRow:
    if i != 45:
        print("Sudoku Is Not Valid For Rows");
        break
else:
    print("Sudoku Is Valid For Rows");

Sudoku Is Not Valid For Rows


In [11]:
checkCol = np.sum(sudoNew, axis = 0);

for i in checkCol:
    if i != 45:
        print("Sudoku Is Not Valid For Columns");
        break
else:
    print("Sudoku Is Valid For Columns");

Sudoku Is Not Valid For Columns


In [12]:
checkRow == 45

array([False,  True,  True,  True,  True,  True,  True,  True,  True])

In [13]:
checkCol == 45

array([ True,  True,  True,  True,  True,  True,  True,  True, False])

In [14]:
sudo = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
]);

sudo

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [15]:
sudo[0:3, 0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [16]:
sudo[0:3, 6:]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [17]:
for i in range(0, 9, 3):
    for j in range(0, 9, 3):
        print(sudo[i: i + 3, j : j + 3]);

[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[6 7 8]
 [1 9 5]
 [3 4 2]]
[[9 1 2]
 [3 4 8]
 [5 6 7]]
[[8 5 9]
 [4 2 6]
 [7 1 3]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[4 2 3]
 [7 9 1]
 [8 5 6]]
[[9 6 1]
 [2 8 7]
 [3 4 5]]
[[5 3 7]
 [4 1 9]
 [2 8 6]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]


In [18]:
for i in range(0, 9, 3):
    for j in range(0, 9, 3):
        n = sudo[i: i + 3, j : j + 3];
        print(n.sum());

45
45
45
45
45
45
45
45
45


In [19]:
import numpy as np; # General Questions

data = np.array([
    [18, 85, 78], # Student Age, Maths Marks & Science Marks
    [19, 92, 88],
    [17, 76, 95],
    [18, 65, 70],
    [20, 90, 85]
]);

data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [20]:
data.shape # Shape Is Instance Attribute

(5, 3)

In [21]:
np.mean(data[:,0]) # Average Age Of Students

np.float64(18.4)

In [22]:
data[:,1] # Maths Marks All Of Students

array([85, 92, 76, 65, 90])

In [23]:
np.max(data[:,2]) # Highest Science Marks

np.int64(95)

In [24]:
data[:,1]

array([85, 92, 76, 65, 90])

In [25]:
data[:,1] > 90

array([False,  True, False, False, False])

In [26]:
data[data[:,1] > 90] # Student Scored More Than 90 In Maths

array([[19, 92, 88]])

In [27]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [28]:
data[:,1] += 5; # Increase Value 5 Maths Marks Of All Students

data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [29]:
data[:,0]

array([18, 19, 17, 18, 20])

In [30]:
data[:,0] < 19

array([ True, False,  True,  True, False])

In [31]:
len(data[data[:,0] < 19]) # Students Are Younger Than 19

3

In [32]:
data[:,1:]

array([[90, 78],
       [97, 88],
       [81, 95],
       [70, 70],
       [95, 85]])

In [33]:
np.mean(data[:,1:], axis = 0) # Calculate Average Marks In Each Students (Column Wise Mean)

array([86.6, 83.2])