In [1]:
import numpy as np;

# **Indexing & Slicing Of Vector**

In [2]:
arr = np.arange(11, 21);

arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
arr[2 : 6]

array([13, 14, 15, 16])

In [5]:
arr_slice = arr[3 : : 2];

arr_slice

array([14, 16, 18, 20])

# **Indexing & Slicing Of Matrix**

In [6]:
arr = np.arange(1,31).reshape(6,5);

arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [7]:
arr[5] # Target On Row

array([26, 27, 28, 29, 30])

In [8]:
int(arr[0, 3]) # Target On Row & Column

4

In [10]:
slice = arr[0 : 2, 1 : 3]

slice

array([[2, 3],
       [7, 8]])

In [11]:
slice = arr[3 : , 2 : ]

slice

array([[18, 19, 20],
       [23, 24, 25],
       [28, 29, 30]])

In [12]:
arr[:, 2] # Target On Column

array([ 3,  8, 13, 18, 23, 28])

# **Boolean Indexing**

In [13]:
arr = np.arange(11, 21);

arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [14]:
bool_index = arr % 2 == 0; # Automatically Run Loop On Array

bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [15]:
arr = arr[bool_index];

print(arr);

[12 14 16 18 20]
