In [1]:
import numpy as np;

# **NumPy Arithmetic Operations**

In [2]:
a1 = np.array([1, 2, 3, 4, 5]);

a2 = np.array([6, 7, 8, 9, 10]);

print(a1);

print(a2);

[1 2 3 4 5]
[ 6  7  8  9 10]


In [3]:
a1 + a2 # In Numpy Operators Can Run Direct Operations But Both Arrays Size Must Be Same

array([ 7,  9, 11, 13, 15])

In [4]:
a1 - a2 # No Need To Run Loop Function Apply Operators

array([-5, -5, -5, -5, -5])

In [5]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [6]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [7]:
a1 // a2

array([0, 0, 0, 0, 0])

In [8]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

# **Broadcasting**

In [9]:
l = [10, 20, 30, 40];

arr = np.array(l);

arr

array([10, 20, 30, 40])

In [10]:
arr + 10

array([20, 30, 40, 50])

In [11]:
arr2 = np.arange(1, 26).reshape(5, 5);

arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [12]:
arr2 = arr2 + 20;

arr2

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45]])

In [13]:
arr2 * 2

array([[42, 44, 46, 48, 50],
       [52, 54, 56, 58, 60],
       [62, 64, 66, 68, 70],
       [72, 74, 76, 78, 80],
       [82, 84, 86, 88, 90]])

# **Deep & Shallow Copy**

In [14]:
arr = np.arange(1, 21);

arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [15]:
slice = arr[ : 5]; # Shallow Copy

slice

array([1, 2, 3, 4, 5])

In [16]:
slice = slice * 10; # Numpy Arrays Create Shallow Copy By Default

slice

array([10, 20, 30, 40, 50])

In [17]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [18]:
arr[4 : 6] * 10

array([50, 60])

In [19]:
arr2 = arr;

arr2[0] = 99;

arr2

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [20]:
arr  # Deep Copy

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [21]:
arr = np.arange(1, 21);

arr

arr2 = arr.copy(); # Shallow Copy

arr2[0] = 99;

print(arr2);

print(arr);

[99  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


# **Matrix Operations**

In [22]:
A = np.array([[1, 2], [3, 4]]);

B = np.array([[5, 6], [7, 8]]);

A

array([[1, 2],
       [3, 4]])

In [23]:
B

array([[5, 6],
       [7, 8]])

In [24]:
print(A * B); # Its Not Matrix Multiplication

[[ 5 12]
 [21 32]]


In [25]:
A @ B

array([[19, 22],
       [43, 50]])

In [26]:
np.dot(A , B)

array([[19, 22],
       [43, 50]])

In [27]:
print(f"""
A: {A}
B: {B}
""");


A: [[1 2]
 [3 4]]
B: [[5 6]
 [7 8]]



In [28]:
A.T # Transpose Of Array

array([[1, 3],
       [2, 4]])

In [29]:
B.T # Row Values Change In Column & Column Change In Row

array([[5, 7],
       [6, 8]])

# **Advance Array Manipulation**

In [30]:
a = np.array([1, 2, 3, 4]); # Stacking Array

b = np.array([5, 6, 7, 8]); # You Can Create Stack Only Vector Array (Single) Not Matrix Array (Double)

In [31]:
np.vstack((a, b)) # V Stack Is (Vertical Stack) Also Row Stack & In Stack Array Pass Must Be In Tuple

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [32]:
np.column_stack((a,b)) # Convert Column Values Into Row Wise 2D Array

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [33]:
np.hstack((a,b)) # Horizontal Stack (Row Wise)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
arr = np.arange(16).reshape(4, 4); # Splitting Array

arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
np.hsplit(arr, 4) # Horizontal Split

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [36]:
np.hsplit(arr, 2) # In Split Only Equal Divison

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [37]:
np.vsplit(arr, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [38]:
np.vsplit(arr, 4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]